# Generated by Django 2.0.7 on 2020-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
